# Generated by Django 2.2.6 on 2019-11-02 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('interestedin', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=100)),
                ('relationshipstatus', models.CharField(choices=[('single', 'Single'), ('committed', 'Committed'), ('inforafling', 'In for a Fling')], max_length=50)),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
