# Generated by Django 2.2.6 on 2019-11-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationshipstatus',
            field=models.CharField(choices=[('single', 'Single'), ('committed', 'Committed')], max_length=50),
        ),
    ]
