# Generated by Django 2.2.6 on 2019-11-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191102_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationshipstatus',
            field=models.CharField(choices=[('single', 'Single'), ('committed', 'Committed')], default='single', max_length=50),
        ),
    ]
