# Generated by Django 2.2.6 on 2019-11-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propose',
            name='status',
        ),
        migrations.AddField(
            model_name='propose',
            name='relationshipstatus',
            field=models.CharField(choices=[('single', 'Single'), ('committed', 'Committed')], default='single', max_length=50),
        ),
    ]
